---
- hosts: all
  become: true
  gather_facts: False
  tasks:
  - name: install python 2 (or python 3 on Ubuntu 20.04)
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal) || apt install -y python-is-python3
    changed_when: False

- hosts: all
  pre_tasks:
    - name: Verify Ansible meets version requirements.
      assert:
        that: ansible_version.major == 2 and ansible_version.minor == 8
        msg: >
          "This currently works with Ansible 2.8"

- hosts: all
  become: true
  #user: root
  roles:
    - {role: deploy-user, github_users: ['mlandauer', 'henare', 'jamezpolley']}
    - cuttlefish-app
